name: Build and Push Dist

on:
  push:
    #branches:
     # - main
    tags:
     - '*'
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove existing dist folder
        run: |
          test -d "./accelerator-home-ui/dist" && rm -rf "./accelerator-home-ui/dist"
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install global tools
        run: |
          npm install -g @lightningjs/cli typescript
          lng --version

      - name: Install project dependencies
        run: npm install
        working-directory: ./accelerator-home-ui

      - name: Build project
        run: lng dist
        working-directory: ./accelerator-home-ui

      - name: verify dist
        run:  test -d "./accelerator-home-ui/dist" && echo "exist" || echo "Not exist"

      - name: Add script tag to index.html
        run: |
          sed -i "/<\/head>/i <script type=\"text/javascript\"> \
          const fbEndpoint = new URLSearchParams(window.location.search).get('__firebolt_endpoint'); \
          if (fbEndpoint) { \
              window.__firebolt = window.__firebolt || {}; \
              window.__firebolt.endpoint = fbEndpoint; \
          } \
          </script>" ./accelerator-home-ui/dist/es6/index.html

      - name: to move dist 
        run: mv ./accelerator-home-ui/dist/es6/* ./accelerator-home-ui/dist
        
      - name: Deploy to local server
        env:
          SERVER_URL:
            http://192.168.1.12:8081/
              # Adjust this URL
        run: |
          # Using curl to upload the build files
          curl -X POST -F "file=@./accelerator-home-ui/dist" $SERVER_URL
