name: Build and Push Dist

on:
  push:
    tags:
      - '*' 
  pull_request:
    types: [closed] 
    branches:
      - main
      - develop
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install global tools
        run: |
          npm install -g @lightningjs/cli typescript
          lng --version

      - name: Install project dependencies
        run: npm install
        working-directory: ./accelerator-home-ui

      - name: Build project
        run: lng dist
        working-directory: ./accelerator-home-ui

      - name: Add script tag to index.html
        run: |
          sed -i "/<\/head>/i <script type=\"text/javascript\"> \
          const fbEndpoint = new URLSearchParams(window.location.search).get('__firebolt_endpoint'); \
          if (fbEndpoint) { \
              window.__firebolt = window.__firebolt || {}; \
              window.__firebolt.endpoint = fbEndpoint; \
          } \
          </script>" ./accelerator-home-ui/dist/es6/index.html

      - name: to move dist 
        run: mv ./accelerator-home-ui/dist/es6/* ./accelerator-home-ui/dist
        
      - name: Identify if triggered by a branch or tag
        run: |
          TRIGGERED_HEAD=${GITHUB_REF#refs/}
          if [${TRIGGERED_HEAD} == "heads/*"]; then
           SET_URL = "${SERVER_BASE_URL}/${{github.ref_name}}/"
          elif [${TRIGGERED_HEAD} == "tags/*"]; then
           SET_URL = "${SERVER_BASE_URL}/releases/${{github.ref_name}}/"
          else
            echo "error occured location not found:"
          fi
          
