name: Build and Push Dist

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install global tools
        run: |
          npm install -g @lightningjs/cli typescript
          lng --version

      - name: Install project dependencies
        run: npm install
        working-directory: ./accelerator-home-ui

      - name: Build project
        run: lng dist
        working-directory: ./accelerator-home-ui

      - name: Verify dist folder
        run: ls -la ./accelerator-home-ui/dist

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Replaced dist folder auto commit from trigger using stefanz
          branch: ma
