name: Build and Push Dist

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install global tools
      - name: Install global tools
        run: |
          npm install -g @lightningjs/cli typescript
          lng --version

      # Install project dependencies
      - name: Install project dependencies
        run: npm install
        working-directory: ./accelerator-home-ui

      # Build the project (create dist folder)
      - name: Build project
        run: lng dist
        working-directory: ./accelerator-home-ui

      # Verify the dist folder
      - name: Verify dist folder
        run: ls -la ./accelerator-home-ui/dist

      # Commit and Push dist folder to the main branch
      - name: Commit and Push dist folder
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions@github.com"
          git add ./accelerator-home-ui/dist
          git commit -m "Auto-commit: Add dist folder"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in token for authentication
